---

gitlab_external_hostname: gitlab.example.com
gitlab_external_schema: https
gitlab_external_url: "{{ gitlab_external_schema }}://{{ gitlab_external_hostname }}"

runner_apt_key_id: F6403F6544A38863DAA0B6E03F01618A51312F3F
runner_apt_key_url: https://packages.gitlab.com/runner/gitlab-runner/gpgkey
runner_apt_repository: "deb https://packages.gitlab.com/runner/gitlab-runner/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main"

ci: False
